version:                      '3.7'

services:
   db:
     image:                   mariadb
     volumes:
       - data_db:/var/lib/mariadb
     restart:                 always
     environment:
       MYSQL_ROOT_PASSWORD:   wp-dev
       MYSQL_DATABASE:        wordpress
       MYSQL_USER:            wordpress
       MYSQL_PASSWORD:        wordpress
     networks:
       - wp

   wordpress:
     depends_on:
       - db
     image:                   wordpress:latest
     volumes:
      - ./tests/wordpress:/var/www/html/wp-content
      - ./tests/wordpress/upload.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./src:/var/www/html/wp-content/plugins/gw2-embeddings
     ports:
       - "8080:80"
     restart:                 always
     environment:
       WORDPRESS_DB_HOST:     db:3306
       WORDPRESS_DB_USER:     wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME:     wordpress
       UPLOAD_MAX_FILESIZE:   64M
       post_max_size:         64M
       max_execution_time:    = 300
     networks:
      - wp

networks:
  wp:

volumes:
  data_db:
